### ISSUE TITLE
keyError 6

### ISSUE THREAD

**Issue by FuYou0723** [LFhase/CIGA#2]
Hi,I'm very inspired by you work,but when i create class SPMotif, it makes a program error that keyError 6 in torch.save(collate(data_list,id)):
in _collcate
  key, [v[key] for v in values], data_list, stores, increment)

**Comment by dingfangyu** [comment]
remove the `pos' attribute in spmotif_dataset.py line 103

data = Data(x=x,
                        y=y,
                        z=z,
                        edge_index=edge_index,
                        edge_attr=edge_attr,
                        # pos=p,
                        edge_gt_att=torch.LongTensor(ground_truth),
                        name=f'SPMotif-{self.mode}-{idx}',
                        idx=idx)

**Comment by LFhase** [comment]
Hi, @ZYF150322661776 Sorry for the late reply. Could you check whether @Arthur-99 's solution works for you? It could be an issue when using  torch_geometric in another version.

BTW, thanks @Arthur-99 for providing the answer : )

**Comment by LFhase** [comment]
I'm closing the issue and feel free to reopen it if you guys have any further questions.
